### ISSUE TITLE
connect is not subject to connect_timeout

### ISSUE THREAD

**Issue by matthiashanel** [nats-io/nats.py#132]
https://github.com/nats-io/nats.py/blob/91f78840c39f6626ffadbd0213cd9d74d0cc539e/nats/aio/client.py#L1140-L1145

wrap in asyncio.wait_for
Same for tls upgrade. 

https://github.com/nats-io/nats.py/blob/91f78840c39f6626ffadbd0213cd9d74d0cc539e/nats/aio/client.py#L1537

**Comment by brianshannan** [comment]
Closed via https://github.com/nats-io/nats.py/pull/166/commits/5d7e01c2c689f2d24baf393e278a6f6e57271779
