### ISSUE TITLE
README update: use `is_async=True`

### ISSUE THREAD

**Issue by roguh** [nats-io/nats.py#135]
I could not see any Exceptions thrown within my coroutines until I set the `is_async` flag.

I suggest enabling the flag in all your examples where you subscribe and use a coroutine as a callback. Example:

```
async def cb():
  if bad():
    raise Exception('error')
nc.subscribe('sample', cb=cb, is_async=True)
```

**Comment by wallyqs** [comment]
is_async deprecated in v1-dev branch now.
