### ISSUE TITLE
Cannot use nats.py with TLS

### ISSUE THREAD

**Issue by Kazmirchuk** [nats-io/nats.py#158]
Hello!
I have  nats-server version 2.1.7 running with self-signed certificates generated with mkcert following these instructions http://docs.nats.io/nats-server/configuration/securing_nats/tls#creating-self-signed-certificates-for-testing

On the client side I have 
```
python --version
Python 3.8.2

pip show asyncio-nats-client
Name: asyncio-nats-client
Version: 0.10.0
```

OS: Windows 10

I cannot connect to NATS. I've tried the example from the main Github page, also from "examples" and "tests" subfolders, and all of them fail with "SSL handshake failed" followed by a traceback pointing to `"TypeError: cannot create weak reference to 'TransportSocket' object"`. The only thing I get in NATS logs (running with -DV) is `"TLS handshake error: EOF"`

Note that I can connect OK to the monitoring endpoint with my browser, and it doesn't show any SSL warnings, because mkcert installed the CA certificate into OS, so the certificates per se are OK.

In order to debug the problem I tried using openssl as a client too:
```
openssl.exe s_client -connect localhost:4222 -CAfile rootCA.pem -tls1_2
```

but it fails with "wrong version number", because NATS requires incoming connections to be always plain TCP in the beginning.

Thanks in advance.

**Comment by meyerje** [comment]
I'm seeing the same behavior, "wrong version number" when using a Windows domain and an internal root ca.

**Comment by meyerje** [comment]
I will note that the golang client does not exhibit this issue.  See below:
GO code that works:
```func ConnectNats() {
    opts := []nats.Option{
        nats.Name("api"),
        nats.RootCAs("/etc/letsencrypt/live/site.local/ROOT-CA.pem"),
        nats.ClientCert("/etc/letsencrypt/live/site.local/fullchain.pem", "/etc/letsencrypt/live/site.local/privkey.pem"),
    }
    opts = setupConnOptions(opts)
    _, err := nats.Connect("tls://api.site.local:4222", opts...)
    if err != nil {
        log.Fatalln(err)
    }
}
```
Python code that does not work:
```import asyncio
import ssl
from nats.aio.client import Client as NATS


async def nats_connect():
    nc = NATS()
    ssl_ctx = ssl.create_default_context(purpose=ssl.Purpose.SERVER_AUTH)
    ssl_ctx.load_verify_locations("ca.pem")
    ssl_ctx.load_cert_chain(certfile="client-cert.pem", keyfile="client-key.pem")
    await nc.connect(
        servers=["tls://127.0.0.1:4222"], tls=ssl_ctx, tls_hostname="localhost"
    )


if __name__ == "__main__":
    asyncio.run(nats_connect())```

**Comment by wallyqs** [comment]
There were many changes to TLS socket handling in recent releases and v2.0.0 refactor so closing for now.
