### ISSUE TITLE
How to get cid/client_id from python client for nats_url:8222/connz monitoring

### ISSUE THREAD

**Issue by imsazzad** [nats-io/nats.py#162]
how to get the cid from python client.
my python client version is 0.10.0
I can see no client_id/cid here.
I need it for monitoring

**Comment by brianshannan** [comment]
The client id can be accessed from the constructed client after connecting, [here](https://github.com/nats-io/nats.py/blob/master/nats/aio/client.py#L1034)

**Comment by charliestrawn** [comment]
closing as I believe Brian's answer addresses the issue
