### ISSUE TITLE
Runtime error: File descriptor is used by transport

### ISSUE THREAD

**Issue by MichalMonko** [nats-io/nats.py#163]
In our project we use NATS client inside celery tasks and sometimes the worker gets stuck constantly raising `errNoServers` when invoking `connect()` method on `Client` instance from `client.py`. By using error callback, following traceback can be seen repeatedly for each subsequent task:

>  Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 469, in _sock_connect
    sock.connect(address)
BlockingIOError: [Errno 115] Operation now in progress
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/nats/aio/client.py", line 1139, in _select_next_server
    limit=DEFAULT_BUFFER_SIZE
  File "/usr/local/lib/python3.7/asyncio/streams.py", line 77, in open_connection
    lambda: protocol, host, port, **kwds)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 941, in create_connection
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 463, in sock_connect
    self._sock_connect(fut, sock, address)
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 477, in _sock_connect
    self.add_writer(fd, self._sock_connect_cb, fut, sock, address)
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 333, in add_writer
    self._ensure_fd_no_transport(fd)
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 244, in _ensure_fd_no_transport
    f'File descriptor {fd!r} is used by transport '
RuntimeError: File descriptor 27 is used by transport <_SelectorSocketTransport fd=27 read=polling write=<idle, bufsize=0>>

This behaviour does not happen each time and may require any number between few and dozen connections to show itself, but once it appears it will appear also in each subsequent connection attempt. Looking this up I've found this thread which shows how to reproduce it in simple way:
https://stackoverflow.com/a/57200947

This has led me to belive that this error is due to invalid closing of sockets created by `asyncio.open_connection`.

Looking further I've found this in `asyncio` documentation:
https://docs.python.org/3/library/asyncio-stream.html?highlight=wait_closed#asyncio.StreamWriter.wait_closed

> coroutine wait_closed()
    Wait until the stream is closed.
    Should be called after close() to wait until the underlying connection is closed.
    New in version 3.7.
 
This coroutine is not used anywhere inside the `client.py`, so I've experimented by creating local copy of this file and adding 
`await self._io_writer.wait_closed()`
after each `self._io_writer.close()` 
call and it seems to solve the issue. It's worth noting that this problem showed itself on python3.7 and 3.8 where this coroutine is available, I don't know if the problem exists on older python versions.

Thanks in advance for assistance on the matter.

**Comment by wallyqs** [comment]
Fixed via #194
