### ISSUE TITLE
Drain Timeout after using request()

### ISSUE THREAD

**Issue by KACAH** [nats-io/nats.py#171]
Hi!

I am experiencing connection drain() Timeout when using request() method of a client on Release v0.11.0. It was fine before, but I am not sure, which exactly version did I use.

Error is happening [here](https://github.com/nats-io/nats.py/blob/ca948843d362dcecf2ecbc99a2ac1ded0c44fa1b/nats/aio/client.py#L560)

The problem is pending_queue.join() of a subscription that was responsible for a request() call (which is finished already with a result). This pending_queue is empty (size = 0), BUT my guess is that task was not properly finished. I think there is 

```python
finally:
    # indicate the message finished processing so drain can continue
    sub.pending_queue.task_done()
```
missing in the request() method [here](https://github.com/nats-io/nats.py/blob/ca948843d362dcecf2ecbc99a2ac1ded0c44fa1b/nats/aio/client.py#L908)

The same way it used in subscribe() method [here](https://github.com/nats-io/nats.py/blob/ca948843d362dcecf2ecbc99a2ac1ded0c44fa1b/nats/aio/client.py#L761)

At least adding mentioned `finally` block solves the problem.

**Comment by wallyqs** [comment]
Thanks @KACAH for the report, will take a look. Which version of Python are you using? And is this using uvloop or TLS? Thanks in advance!

**Comment by KACAH** [comment]
> Python 3.8.5 (default, Sep  5 2020, 10:50:12) 
[GCC 10.2.0] on linux

uvloop: **yes**
TLS: **no**
