### ISSUE TITLE
Implement multithreading with subscriptions (concurrent execution) like Flask routes

### ISSUE THREAD

**Issue by shayan09** [nats-io/nats.py#180]
Hi! I am moving my code from a `flask` app to `NATS.` `Flask`, by default is multi-threaded and I am trying to do that as well with `nats` but have struggled to run _co-routines_ **concurrently**. As far as I understand, when you execute a _co-routine_, it blocks the event loop until it is completed even if that co-routine contains I/O operations.  

The flask app had two routes: 
1. **/train:** Large task of training a ML model and takes time.
2. **/predic**t: Small high priority task.

In my flask app, I could call the **/predict** route while **/train** was running and get the result immediately. However, with the `asyncio` approach in NATS, the predict callback does not even start until the train callback is completed. They are always executed sequentially. I have tried to execute the _LARGE TASK_ and _SMALL TASK_ as threads, but in Python you cannot get a `return` value of the thread unless you use a `Queue`. However, `Queue` is not a good option when you start threads randomly. 

Is there a possible solution to execute multiple callbacks **concurrently**? I have attached a sample code to better understand the terms I am using to describe my problem.

```python
     async def train(msg):
        """
        The bot train requests come here
        :return:
        """
        subject = msg.subject
        reply = msg.reply
        data_train = json.loads(msg.data.decode())
        routes.logger.info("Received a message on '{subject} {reply}': {data}".format(
            subject=subject, reply=reply, data=data_train))

        routes.logger.debug('subscribe/train: Train data: {}'.format(data_train))
        data = routes.train(data_train) // LARGE TASK
        routes.logger.info(data)
        await nc.publish(msg.reply, json.dumps(data).encode())
        subscriber = 'nlu.{}.predict.{}'.format(lang, data['model'].split('_')[1])
        if subscriber not in current_subscribers:
            current_subscribers[subscriber] = await nc.subscribe(subscriber, cb=predict)
            routes.logger.info('Added subscription: {}'.format(subscriber))

    async def predict(msg):
        """
        The bot predict requests come here
        :return:
        """
        subject = msg.subject
        reply = msg.reply
        data_predict = json.loads(msg.data.decode())
        routes.logger.info("Received a message on '{subject} {reply}': {data}".format(
            subject=subject, reply=reply, data=data_predict))
        data = routes.predict(data_predict) // SMALL TASK
        routes.logger.info(data)
        await nc.publish(msg.reply, json.dumps(data).encode())

await nc.subscribe('{}.train'.format(connection), cb=train)
await nc.subscribe('{}.predict'.format(connection), cb=predict)
```

**Comment by wallyqs** [comment]
Hi @shayan09 the example may look a bit involved but I've been thinking whether we could have a library that can help with some of this too.  The two things that you will need is to use a ThreadPoolExecutor for the blocking tasks, for example assuming that here ` data = routes.train(data_train)` is a blocking task that takes several seconds and could block the main thread, then that would be scheduled into a thread pool from the executor to parallelize these blocking tasks without blocking the main thread.

Then, since each one of the messages from the nats library will be processed sequentially, it is needed to create an asyncio.Task for each one of these messages in case more concurrency for asyncio is needed.  The example then would look something like this:

```python
import asyncio
import nats
import concurrent.futures
import time

def train(msg):
    print("->> Train task started...", msg.data)
    time.sleep(1) # seconds
    print("<<- Train task done...", msg.data)
    return f"DONE: {msg.data.decode()}"

async def run(loop):
    nc = await nats.connect(servers=["nats://localhost:4222"])

    # Executor for tasks in parallel.
    executor = concurrent.futures.ThreadPoolExecutor(
        max_workers=5,
    )

    async def train_handler(msg):
        print(f"Received '{msg.subject}' request...")

        async def new_task(msg):
            result = await loop.run_in_executor(executor, train, msg)
            await nc.publish(msg.reply, result.encode())

        # TODO: This is a future that has to be gathered before closing
        # the connection with nc.close()
        asyncio.create_task(new_task(msg))

    await nc.subscribe("train", cb=train_handler)
    print("Listening for train tasks...")

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(run(loop))
    loop.run_forever()
```

Example result:

```
seq 10 | parallel -j 10 nats-req train
Published [train] : '6'
Received  [_INBOX.vK5PUHK2wzhl1VpTYS4BGf.CtwhcU8H] : 'DONE: 6'
Published [train] : '3'
Received  [_INBOX.nxY7QSd5464dfCMtGrrpSx.TOaDG5UC] : 'DONE: 3'
Published [train] : '2'
Received  [_INBOX.64yjDt8CNT36fgpvxO5QRP.adjqtxgl] : 'DONE: 2'
Published [train] : '5'
Received  [_INBOX.tKCIbR7p0zK30vMe43EVY4.leVMwo8z] : 'DONE: 5'
```

**Comment by shayan09** [comment]
Hi @wallyqs! Thank you for your response.

I did try your solution with a few modifications and it is definitely better than before, but it takes way too long for the `predict` request to get served (most times sequentially like before under stress). I agree that `train` is a computation heavy task that uses `Spacy` in the background, but **Flask**'s way of **multi-threading** is way faster and smoother. For some reason I also get `Spacy` threading issues because it loads a new model for each thread. That's a whole different issue though.

Could we possibly dig into **multi-threading** and implement something like a basic **Flask** app does (without `gunicorn` and all that cool stuff) in the near future for **nats**?

**Comment by wallyqs** [comment]
Hi @shayan09 yes this is something that can look into in the near future, like binding each handler into its own thread pool executor maybe. One thing to consider as well when there are blocking issues is to wrap the NATS connection into its own component and with its own thread (something like:  https://github.com/nats-io/nats.py/blob/master/examples/coroutine_threadsafe.py#L31) and then whenever receive a task use `syncio.run_coroutine_threadsafe` so that the client can be called from another thread.

**Comment by charliestrawn** [comment]
It's an interesting idea and worth looking into, but IMO that brings a lot of potential complexity that should probably not live in this repo. Flask is a (micro) web framework, while this is a library for talking to a nats-server or clusters. I think we want to keep this repo simple, focused, and flexible. This allows consumers to wrap or extend it in their own projects or custom frameworks that handle things like threading.

**Comment by wallyqs** [comment]
Recommend to take a look at this project which feels Flask like but for NATS: https://github.com/lwinterface/panini
