### ISSUE TITLE
Jetstream messages not returning when using request() without callback

### ISSUE THREAD

**Issue by dmglennie-diveplane** [nats-io/nats.py#192]
We're admittedly quite early users of jetstream, and I understand that there are no specific accommodations made for it in the client - but thought I'd raise this anyway, perhaps it is useful - or someone has some insight I'm missing.

If you use the nc.request() with no callback, the client will use the new style req/resp .... the implementation involves a token, embedded in the subject, principally to lookup a future in a map.

This doesn't work when sending a req to a jetstream '$JS.API.CONSUMER.MSG.NEXT.<stream>.<consumer>' queue, .... since the reply subject is changed (by jetstream) to be the original message subject.  The subject in the reply therefore doesn't contain the token.  The client code attempts the future lookup using a token from the (jetstream altered) subject, but that obviously doesn't work.

The observed behavior is that when using nc.request() in a blocking fashion with jetstream, it will hang until the timeout.  Internally [this ](https://github.com/nats-io/nats.py/blob/045f7bf23450599c7d8ea85632fbbfef61211f7f/nats/aio/client.py#L911) keyerror is caught  ... but not dealt with (as normally it would just mean the future had been handled)

If I get a moment I'll try and put together a quick example.

Thanks

**Comment by ColinSullivan1** [comment]
Equivalent functionality to remap the JS response in nats.go can be found [here](https://github.com/nats-io/nats.go/blob/acca6d69b4e3ee1abef2b96cae85a3878aa2a520/nats.go#L3049).

**Comment by dmglennie-diveplane** [comment]
Got it.  So with that fix, it will work if there is one reply in the map (probably ok for our use case), but not if there is a lot of activity?  I might try and make that small change, if that approach seems to work on the go side.

**Comment by hooksie1** [comment]
Were you able to figure this out? Currently looking to implement jetstream but not sure how to go forward with this. Using a callback seems to work for a short amount of time, but then we see a weird issue with empty messages. Hoping to use the new style without the callback.

**Comment by dmglennie-diveplane** [comment]
Hi - sorry, I thought I'd included this, but evidently not.   So we were able to use the existing timed_request() function, with no callback  - that works fine - at least for our use case - as the implementation doesn't rely on the subject in the same way.

**Comment by hooksie1** [comment]
Ah nice, I'll give that a shot. Thanks!

**Comment by 300LiterPropofol** [comment]
Hi @dmglennie-diveplane, thank you for your pioneer try of Jetstream on python client. 
Sorry I didn't get it very clearly. Do you mean that currently python nats client already support usage of jetstream and the current timed_request() syntax can work well with jetstream? 
Also looking forward to your example that you mentioned!

**Comment by hooksie1** [comment]
For us the `timed_request()` method worked but we had to manually send an ack afterwards. The ack passed in `timed_request` didn't seem to be sent and we ended up with retries. So if you publish a nil payload to `msg.reply` it seems to work correctly.

**Comment by wallyqs** [comment]
Pull subscribers are now supported in the client: https://nats-io.github.io/nats.py/modules.html#nats.js.client.JetStream.pull_subscribe
