### ISSUE TITLE
Support headers

### ISSUE THREAD

**Issue by gucharbon** [nats-io/nats.py#195]
Hi,

First of all thanks for offering to the community this library as well as all the NATS ecosystem.

I saw in the Projects section that [header support is included in the v1.0.0 milestone](https://github.com/nats-io/nats.py/projects/1#card-51369420).

We're quite in need of this feature, and have a working solution where we enforce some schema on message data, something like:

```json
{
  "__data__": <actual_data>,
  "__context__": <trace_context>
}
```

The problem with this approach, is that we MUST serialize all our messages to JSON format (we could use another format, but the constraint of enforcing schema on the payload is the same).
> BTW we also use Typescript, and had to implement this feature too using `ts-nats`

We're in the process of rewriting our internal library, and are wondering if we should port this "solution" to our new version, or if we should wait for this feature to be implemented in `nats.py`.

If you could give us a time estimate of the implementation, it would help us in taking a decision.

More over, I'm not familiar with NATS code base, and don't really know how to tackle this issue, but if there are things that seem doable for first contributors, don't hesitate to point us in the right direction.

Thanks in advance 🙇

**Comment by wallyqs** [comment]
Hi @gucharbon this is planned to be worked on soon after the NATS v2.2 release of the nats-server, after which will be spending more time on the clients. I'd estimate headers in the nats.py client to be available around the first week of March.

**Comment by wallyqs** [comment]
@gucharbon some more info, the next version of the nats.py client can be found here so if that would be the place to directly contribute to that release: https://github.com/nats-io/nats.py/tree/v1-dev 
It is not backwards compatible in some areas but it should be closer in usage to how the Go client works now. This is the reference implementation of headers from the Go client: https://github.com/nats-io/nats.go/pull/560/files
One of the first things to tackle is to decide how to adopt to parse the headers that become the field of a message for example: https://github.com/nats-io/nats.go/blob/master/nats.go#L2830

**Comment by gucharbon** [comment]
Thanks for the quick response. A release in march would be really nice ! I read the links you provided as well as the `nats.protocol.parser`, but too be honest, we have many other problems to tackle other than NATS header support and will be focusing on them till next month. If by any chance we've got time to work on the subject before you actually start working on it, we'll share it with you.

**Comment by gcolburn** [comment]
Hi @wallyqs. Any updates on an estimated timeline for header support in nats.py? Thanks!

**Comment by danylott** [comment]
Hi @wallyqs, thank you for all work you already done in NATS.io. Still looking forward for headers support in nats.py :)

**Comment by reegeek** [comment]
Hi @wallyqs thank you for all work already done.
I use nats to communicate between a server write in .net and a client in python.
I use header in C#, I would like to use it also in python.
Do you have any visibility as to when headers will be taken into account in python ?
Regards

**Comment by charbonnierg** [comment]
@wallyqs Would it be possible to merge changes related to header found in js-ctx branch without including changes related to Jetstream ? (I.E, only header support and new request/reply pattern) ? I can rebase js-ctx branch on master, add some typing and open a PR if it's ok with you

**Comment by drewcorlin1** [comment]
Hi @wallyqs - I see that there have been comments on this thread recently, so apologies for all the pings, but I also wanted to check on the status of this feature. Also more generally is this library going to be supported going forward? My team would like to use NATS and Jetstream, but python is a large part of our stack so it is probably a non-starter for us if we can't rely on the python library being as up to date as other languages.

**Comment by charbonnierg** [comment]
I  think this is supported since https://github.com/nats-io/nats.py/commit/90763db5aa6db302cb0f087a93c663f332b7492d . We should close this issue.

**Comment by wallyqs** [comment]
This has been finally supported so closing... https://github.com/nats-io/nats.py/releases/tag/v2.0.0rc1
`publish` and `request` have a `headers={}` argument that takes a dictionary with the headers: 
https://nats-io.github.io/nats.py/modules.html#nats.aio.client.Client.publish
