### ISSUE TITLE
DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10

### ISSUE THREAD

**Issue by 2-5** [nats-io/nats.py#197]
`DeprecationWarning` raised for `loop` argument usage at these location (there could be more which my code didn't hit):

https://github.com/nats-io/nats.py/blob/master/nats/aio/client.py#L311
https://github.com/nats-io/nats.py/blob/master/nats/aio/client.py#L725
https://github.com/nats-io/nats.py/blob/master/nats/aio/client.py#L1723

Code is run with warning logging enabled: `python -W default test.py`

**Note the *scheduled for removal in Python 3.10* part in the warning, this might break nats.py in Python 3.10.**

**Comment by wallyqs** [comment]
Thanks, in the v1 branch this has been addressed already.

**Comment by roguh** [comment]
When will v1 be released?

**Comment by roguh** [comment]
The changes will be released soon: https://github.com/nats-io/nats.py/discussions/212

**Comment by wallyqs** [comment]
Released as part of this https://github.com/nats-io/nats.py/releases/tag/v2.0.0rc1
