### ISSUE TITLE
Can NATS keep messages in memory if no workers are online at the moment (producer-consumers pattern)?

### ISSUE THREAD

**Issue by ArtyomKozyrev8** [nats-io/nats.py#209]
I would like to use NATS to distribute tasks among several worker-processes. Everything works as expected if I have at least one worker "online", but if there are no worker-processes, messages are just thrown away, when I turn on one worker I got no messages (which were created when it was not online).

I know how to do it with RabbitMQ, but is it possible to do it with NATS?

I do project in Python, producer-process in aiohttp, worker-processes are also in Python and do some CPU-heavy tasks.

**Comment by charbonnierg** [comment]
As per [the documentation](https://docs.nats.io/nats-concepts/intro):

> NATS core offers an at most once quality of service. If a subscriber is not listening on the subject (no subject match), or is not active when the message is sent, the message is not received. This is the same level of guarantee that TCP/IP provides. Core NATS is a fire-and-forget messaging system, will only hold messages in memory and will never write messages directly to disk. If you need higher levels of service, you can use [NATS JetStream](https://docs.nats.io/jetstream/jetstream) or build additional reliability into your client applications with proven and scalable reference designs such as [acks](https://docs.nats.io/nats-concepts/acks) and [sequence numbers](https://docs.nats.io/nats-concepts/seq_num).

**Comment by ArtyomKozyrev8** [comment]
@charbonnierg so in other words jetstream Python client is not ready to use at the moment? I would like to try anything else than RabbitMQ, so found NATS and decided to do some experiments.

I try to run NATS/Jetstream in container for tests the following way:

```docker run -p 4222:4222 nats -js --name test_server --cluster_name test_cluster```

Then I just try to run the first example from STAN documentation and get Timeout Error, though test_cluster should have been created, container runs fine:

```
import asyncio
from nats.aio.client import Client as NATS
from stan.aio.client import Client as STAN 

async def run(loop):
    nc1 = NATS()
    sc1 = STAN()
    await nc1.connect(servers=["nats://localhost:4222"], io_loop=loop)
    await sc1.connect("test_cluster", "client-1", nats=nc1) # Get Timeout error here
...
```

I guess that I do something wrong when running container or it is really connector issue. Please advise.

**Comment by charbonnierg** [comment]
In  your example, you're trying to use [NATS Streaming Server](https://github.com/nats-io/nats-streaming-server). You can check the [introduction](https://docs.nats.io/nats-streaming-concepts/intro) but keep in mind:

> The NATS Streaming Server is being deprecated. Critical bug fixes and security fixes will be applied until June of 2023. NATS enabled applications requiring persistence should use JetStream.

As for your example it works fine **if you start an NATS Streaming Server**:

- In a terminal (or using a [Docker container](https://hub.docker.com/_/nats-streaming): `docker run -d -p 4222:4222 -p 8222:8222 nats-streaming`):

```bash
nats-streaming-server --cluster_id test_cluster
 ```

- In Python:

```python
import asyncio
from nats.aio.client import Client as NATS
from stan.aio.client import Client as STAN

async def main():
    nc1 = NATS()
    sc1 = STAN()
    await nc1.connect(servers=["nats://localhost:4222"])
    await sc1.connect("test_cluster", "client-1", nats=nc1)


asyncio.run(main())
```

**Comment by charbonnierg** [comment]
Note that in your example, you're starting an NATS Server with JetStream enabled, not an NATS Streaming Server. Those are two different things

**Comment by ArtyomKozyrev8** [comment]
@charbonnierg thank you very much to your support!
