### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by jinyongyoo** [nats-io/nats.py#215]
When will there be new release of this package on PyPI? Seems like current version 0.11.4 doesn't work with the example code in README.md.

**Comment by roguh** [comment]
See the author's response at https://github.com/nats-io/nats.py/discussions/212

**Comment by roguh** [comment]
Also, you can checkout the tag to see the readme for the version you're likely using: https://github.com/nats-io/nats.py/tree/v0.11.4

**Comment by jinyongyoo** [comment]
Thanks!

**Comment by wallyqs** [comment]
fyi I just pushed a pre-release version of the library that can be installed as follows if want to give it a try already:

```
pip install nats-py==2.0.0a1
```
