### ISSUE TITLE
Publishing Does Not Send Message

### ISSUE THREAD

**Issue by baloian** [nats-io/nats.py#217]
Hi, I am using Python client as a publisher and Nodejs client as a subscriber. When I do 
```python
await nc.publish("foo", b'Hello')
```
It does not send data. At least subscriber does not receive it. When I invoke the drain() method after publishing it the subscribers receives the message.

```python
await nc.publish("foo", b'Hello')
await nc.drain()
```

Here is my Python code
```python
async def main():
    nc = await nats.connect()
    await nc.publish("foo", b'Hello')
    time.sleep(10)
    await nc.publish("foo", b'World')
    # As soon as I run the following it sends both messages at the same time.
    # I expect to send "Hello" message and then after 10 seconds the "World" message.
    await nc.drain()


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
    loop.close()
```

Am I missing something?

**Comment by wallyqs** [comment]
have you tried doing `await nc.flush()` before exiting?

**Comment by baloian** [comment]
Thanks! It solved the problem. It would be nice to mention this on README that we should run `await nc.flush()` after every publishing or a list of publishing we want to publish.

I am closing the issue.
