### ISSUE TITLE
Jetstream pull subscriber gets 408/404 status messages in response from fetch

### ISSUE THREAD

**Issue by hammadk373** [nats-io/nats.py#238]
Found a bug/typo in the JS client's `_fetch_one` function code: https://github.com/nats-io/nats.py/blob/main/nats/js/client.py#L631. 

Right now we get `408` status messages back from the fetch request like regular messages if those have already been added to the local `_pending_queue`

Based on the comment just before that line and the expected behaviour I believe that line should be `continue` not `pass` when `status` is not None

**Comment by wallyqs** [comment]
Thanks for the bug report... yes you are right that it should have been `continue`...

**Comment by wallyqs** [comment]
Fixed via #239 -- just pushed to pypi as well with the patch, thanks again.
