### ISSUE TITLE
APIError code=408 raised by the pull subscriber after old pull requests expire.

### ISSUE THREAD

**Issue by hammadk373** [nats-io/nats.py#241]
Following on from #238. I am working on an issue where the 408 status messages from Jetstream leak out of the library and into our code as exceptions. 

When Jetstream cleans up previously expired pull requests, it generates a 408 status message. As far as I understand this message is supposed to be handled in the python client library and be transparent to the user of the library. However that is not the case.

This sample code: https://gist.github.com/hammadk373/95cac1cfa19a6f84ba307986722f49b7 can be used to reproduce the issue. 

Pre-create the stream and consumer:
- `nats str add STR --subjects "STR.*" --ack --max-msgs=-1 --max-bytes=-1 --max-age=1y --storage file --retention limits --max-msg-size=-1 --discard=old --dupe-window=2m --replicas=1 --max-msgs-per-subject=-1`
- `nats con add STR PULL_CON --filter STR.PULL --ack explicit --pull --deliver new --max-deliver=-1 --sample 100 --max-pending=1 --replay=instant --wait=1s --max-waiting=10`
(notice the `--max-waiting=10` setting in the consumer)

Then run the attached code, pointing to your Jetstream instance.

Every time the waiting pulls reach max-waiting (10) config, the Jetstream creates 408 messages, one of which leaks out to the user code.

The error generated is:
```
Traceback (most recent call last):
  File "/Users/khanhca.ibm.com/Projects/CDP/PythonTest/temp.py", line 17, in main
    msgs = await pull_sub.fetch(batch=1, timeout=1)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/nats/js/client.py", line 615, in fetch
    msg = await self._fetch_one(batch, expires, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/nats/js/client.py", line 656, in _fetch_one
    raise nats.js.errors.APIError.from_msg(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/nats/js/errors.py", line 66, in from_msg
    raise APIError(code=int(code), description=desc)
nats.js.errors.APIError: nats: APIError: code=408 err_code=None description='Request Timeout'
```

Based on the `JetStream._is_processable_msg` function 408 and 404 status messages should be ignored (it returns False). However, the `_fetch_one()` code raises them as an APIError.

I am not sure what the fix would be, maybe if `_is_processable_msg` returns `False`, make a second request to the consumer with the remaining timeout to get the next message. 

Alternatively, is there a reason why `_fetch_n` cannot be used with a batch size of 1 instead of `_fetch_one`? Based on my limited experimentation and looking at the code it seems like `_fetch_n` handles the case correctly.

**Comment by wallyqs** [comment]
Hi @hammadk373, have you tried with the patched version of the client? I cannot reproduce with your code using that release:

```
python3 examples/asdf.py 
pulls waiting: 0/10
timeout
pulls waiting: 1/10
timeout
pulls waiting: 2/10
timeout
pulls waiting: 3/10
timeout
pulls waiting: 4/10
timeout
pulls waiting: 5/10
timeout
pulls waiting: 6/10
timeout
pulls waiting: 7/10
timeout
pulls waiting: 8/10
timeout
pulls waiting: 9/10
timeout
pulls waiting: 10/10
timeout
pulls waiting: 1/10
timeout
pulls waiting: 2/10
timeout
pulls waiting: 3/10
timeout
pulls waiting: 4/10
timeout
pulls waiting: 5/10
timeout
pulls waiting: 6/10
timeout
pulls waiting: 7/10
timeout
pulls waiting: 8/10
timeout
pulls waiting: 9/10
timeout
pulls waiting: 10/10
timeout

```

**Comment by hammadk373** [comment]
I am using `v2.0.0rc5` and I get:
```
pulls waiting: 3/10
timeout
pulls waiting: 4/10
timeout
pulls waiting: 5/10
timeout
pulls waiting: 6/10
timeout
pulls waiting: 7/10
timeout
pulls waiting: 8/10
timeout
pulls waiting: 9/10
timeout
pulls waiting: 10/10
APIERROR: timeout
Traceback (most recent call last):
  File "/Users/khanhca.ibm.com/Projects/CDP/PythonTest/temp.py", line 17, in main
    msgs = await pull_sub.fetch(batch=1, timeout=1)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/nats/js/client.py", line 615, in fetch
    msg = await self._fetch_one(batch, expires, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/nats/js/client.py", line 656, in _fetch_one
    raise nats.js.errors.APIError.from_msg(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/nats/js/errors.py", line 66, in from_msg
    raise APIError(code=int(code), description=desc)
nats.js.errors.APIError: nats: APIError: code=408 err_code=None description='Request Timeout'
pulls waiting: 1/10
timeout
pulls waiting: 2/10
```

I will investigate some more on my end. maybe an update to the latest NATS might help.

**Comment by hammadk373** [comment]
Updating to the latest NATS Server (v2.6.6) fixed the problem. Closing this issue.

**Comment by wallyqs** [comment]
Nice, thanks for the update
