### ISSUE TITLE
[Question] Create muiltiple non-queue push subs

### ISSUE THREAD

**Issue by c0rv4x** [nats-io/nats.py#246]
Hi! 

I have a question on how to correctly use multiple non-queue Jetstream subscribers. So I have the following code:

```python
import asyncio
import nats

async def main():
    nc = await nats.connect()
    js = nc.jetstream()

    await js.add_stream(name="sample-stream12", subjects=["x_name"])
    await js.subscribe(subject="x_name", queue=None, durable="x_name")
    await js.subscribe(subject="x_name", queue=None, durable="x_name")

    await nc.close()


if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(main())
```

Upon running it returns `nats.js.errors.Error: nats: JetStream.Error consumer is already bound to a subscription`. I guess the thing is that the library is trying to bind another subscriber to an existing consumer by the same name?

I am having multiple subscribers in different processes to a single non-queue in my case

**Comment by wallyqs** [comment]
Yes you can try pull subscribers to have multiple clients be able to fetch from same durable, or use queue subscribers. A plain subscriber with a durable can only have a single subscription at the same time.

**Comment by c0rv4x** [comment]
@wallyqs  Thanks for clarifying!
