### ISSUE TITLE
PullSubscribeTest.test_fetch_n fails locally

### ISSUE THREAD

**Issue by orsinium** [nats-io/nats.py#269]
The test `tests/test_js.py::PullSubscribeTest::test_fetch_n` fails locally, doesn't matter how many times I retry. It fails the assertion `self.assertTrue(info.num_waiting <= 1)`. Here, `info.num_waiting` is 2 for me.

+ nats.py version: the latest `main` branch (`24640cd9264f0d854e667c20c5a7042023993a85`)
+ nats-server version: `v2.6.6`.
+ OS: `Linux 5.4.0-96-generic #109-Ubuntu SMP Wed Jan 12 16:49:16 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

Please, let me know if you need any additional information.

**Comment by wallyqs** [comment]
You need to use `2.7.1` for some of these tests, the pull subscribe behavior has been changing often lately. Maybe we should relax some of these checks on the tests and only test that the messages are being delivered.

**Comment by orsinium** [comment]
Just tested it with 2.7.2. All works just fine, thank you :)
