### ISSUE TITLE
ssl_context referenced before assignment

### ISSUE THREAD

**Issue by Basketballforce** [nats-io/nats.py#292]
On python 3.9.

I was testing the quickstart/examples found on nat.io and the github repo but, ran into this issue:

When running the example, an UnboundLocalError occurs in nats/aio/client.py stating that local variable ssl_context referenced before assignment

The odd thing is the specific line from the error traceback if from line 1741 in which 

`if ssl_context is None`

Any insight on why this is occuring?

Thank you!

**Comment by Basketballforce** [comment]
Unrelated Sidenote: If running the python client in windows and you get a "event loop closed error" you can resolve this by adding

`asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())`

Before calling asyncio functions/calls

**Comment by wallyqs** [comment]
Fixed via #293

**Comment by Basketballforce** [comment]
Thanks! :)
