### ISSUE TITLE
Example reconnect_cb syntax wrong

### ISSUE THREAD

**Issue by 300LiterPropofol** [nats-io/nats.py#325]
Hello!

I would like to report a syntax bug in one of your examples in this repo.

https://github.com/nats-io/nats.py/blob/3be8eda7f9f663c961ada7ee8bf74308ccf7178e/examples/connect.py#L12

In the `reconnected_cb`, there is no such variable named nc, so that reconnected nc will not work. During reconnection, that callback does not print any logs. 

So I removed the `nc.connected_url.netloc` in the log text, and the callback works properly.

**Comment by 4383** [comment]
This callback is in inner function, who needs to know the client during its init. The client object also needs to know this callback during its init, so it's a bit of a snake that kills its tail.
