### ISSUE TITLE
lack of nc.flush() documentation

### ISSUE THREAD

**Issue by HYAR7E** [nats-io/nats.py#336]
As stated in this issue #217 from around 10 months ago the docs never state the need to execute `await nc.flush()` after publishing a message.
I had the very same problem today, and after checking out the [docs](https://nats-io.github.io/nats.py/modules.html) I noticed that most code examples use flush after publish, and so I figured it out (most of my colleagues have been falling into the same issue when they start with nats).

I'd like to contribute improving the docs to at least give a hint of using flush, or when to use it.
Is there a way to edit the docs and add this information, if it already exists: where is it and can we give it a little more visibility?

As a last note, I found the repo has a [folder](https://github.com/nats-io/nats.py/tree/main/examples) full of examples but the docs don't mention it at all, I suggest to give it more visibility too.

If I can be of any help please reach out.

**Comment by wallyqs** [comment]
Generally a `flush` is only needed when about to close the connection to ensure that the messages are sent before closing, but agree that maybe we should mention that in the docstring from publish maybe here: https://github.com/nats-io/nats.py/blob/main/nats/aio/client.py#L689-L702
The docs are a branch in the repo which can be found here as well: https://github.com/nats-io/nats.py/tree/docs/source

**Comment by HYAR7E** [comment]
@wallyqs I made a short PR #337 to add `flush` in the HelloWorld example, I can add it to the docstring too but imo just the HW example is enough for people to know about flush and make their own way in the docs

**Comment by HYAR7E** [comment]
PR is merged so I'm closing this
