### ISSUE TITLE
NATS JetStream fetch from pull subscribe returns None instead of Msg object

### ISSUE THREAD

**Issue by ronigober** [nats-io/nats.py#339]
Hey.
We have a strange bug.
We are using NATS JetStream, so we create pull subscribe and fetching the messages.
Infrequently we get from the fetch function of the pull subscribe None instead of Msg object.
We can't reproduce this bug because it's inconsistent and happens rarely.
We searched in the documentation and in the source code itself and we couldn't trace when None should return instead of the Msg object, it's seems like it not something that suppose to happen.
Thanks.

**Comment by wallyqs** [comment]
Thanks for the report, just checking are you using latest nats-py?

**Comment by ronigober** [comment]
We currently using the 2.1.2 version.
We will update to the latest and check if it's still happening.
We will update you if it's changed something.
Thanks.

**Comment by charbonnierg** [comment]
We also encountered this issue with nats-py v2.1.3, we did not really dig into the problem  when it happened (August 23rd according to commits), we only added an if statement to check for the return value of the `.fetch()` method in our code:

```python
class PullSubscriptionIterator:
    def __init__(self, subscription: JetStreamContext.PullSubscription):
        self.subscription = subscription
 
    def __aiter__(self) -> MySubscription:
        return self

    async def __anext__(self) -> Msg:
        while True:
            # Fetch next message
            msg, *_ = await self.subscription.fetch(timeout=None)
            # Stop iteration if msg is falsy
            # Without those lines, we encountered cases where msg was None
            # We prefer stopping iteration at this point and let the caller iterate a second time if needed
            if not msg:
                raise StopAsyncIteration
            yield msg
```

I tried to reproduce the issue locally with nats-py v2.1.3, and even after running the same script several times with a stream holding quite a lot of messages, but I did not reproduce the issue.

**Comment by ronigober** [comment]
@charbonnierg Thanks for your sharing!
It exactly what happened to us, but we didn't know if the None value is another sign for StopIteration or just a bug, 
because we didn't see any mention to it in the documentation or in the source code.
We updated the NATS Python client to its latest version, and so far we didn't got this bug again.
If something will change I will let you all know.
Thanks everyone for your help!
