### ISSUE TITLE
Documentation should be on the sidebar

### ISSUE THREAD

**Issue by bvanelli** [nats-io/nats.py#359]
Currently it's a bit hidden that the project actually has documentation, but it does!

- [ ] Add this link https://nats-io.github.io/nats.py/ to the sidebar just like other github projects:

![image](https://user-images.githubusercontent.com/8211602/193028987-ab61d2d1-32d3-4b6f-bfaa-c82132b7f461.png)

- [ ] Include link to the documentation on the README.

**Comment by wallyqs** [comment]
Not sure how to enable this but I'd like to...  🤔

**Comment by wallyqs** [comment]
I put the link like this for now: 
<img width="322" alt="image" src="https://user-images.githubusercontent.com/26195/194440180-7f849a74-2e64-4826-b311-49de04233bf9.png">
