### ISSUE TITLE
asyncio-nats-client-0.11.5 is this compatible with python 3.10.8 and above?

### ISSUE THREAD

**Issue by napoleonp** [nats-io/nats.py#400]
Seeing the following traceback, while running doing natsclient.connect with python 3.10.8.

  File "/usr/lib/python3.10/site-packages/nats/aio/client.py", line 310, in connect
    self._flush_queue = asyncio.Queue(
  File "/usr/lib/python3.10/asyncio/queues.py", line 34, in __init__
    super().__init__(loop=loop)
  File "/usr/lib/python3.10/asyncio/mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Queue() since it is no longer necessary

Any suggestions on how to resolve this? Using Alpine 3.16 which is packaged with 3.10.8.

**Comment by wallyqs** [comment]
Hi @napoleonp you could try with with `nats-py` instead which is compatible.

**Comment by orsinium** [comment]
Are you sure you're using the latest version of nats-py? Because it doesn't use `loop` in the relevant code:

https://github.com/nats-io/nats.py/blob/main/nats/aio/client.py#L448

**Comment by napoleonp** [comment]
> Hi @napoleonp you could try with with `nats-py` instead which is compatible. https://pypi.org/project/nats-py/

Thank you Quevedo, that was useful. Moved to nats-py.
