### ISSUE TITLE
loading nkeys seed directly instead of file

### ISSUE THREAD

**Issue by darylac** [nats-io/nats.py#404]
I am currently loading nkeys seed by giving the file path as string to `nkeys_seed` argument in nats `connect` function, which works great. But, I wanted to know if we can also give a seed value directly instead of loading from a file?

**Comment by JarleB** [comment]
Yes this would be helpful so that one could use the string directly as an output from another program or funciton

**Comment by darylac** [comment]
In my case, I am reading a value from environment variable and writing it to a file on application startup and provide that file path as `nkeys_seed` argument. (The environment variables are loaded from kubernetes secret that is shared among multiple applications).

**Comment by tkeller-moxe** [comment]
Would love to see the ability to pass an nkey_seed directly as well instead of a file as well1

**Comment by darylac** [comment]
Closing this issue as it is fixed in #468
