### ISSUE TITLE
Question: Deterministic Subject token Partitioning example

### ISSUE THREAD

**Issue by alexreznikoff** [nats-io/nats.py#414]
Hi! Сan you add an example for python how to write publishers and subscribers using  [Deterministic Subject token Partitioning](https://docs.nats.io/nats-concepts/subject_mapping#deterministic-subject-token-partitioning)

if i created 3 partitions should i create 3 subscribers (one for each partition)?
Is there no automatic rebalancing of partitions by subscribers?

**Comment by jnmoyne** [comment]
There is nothing to do on the publishers, the Core NATS subject mappings are configured either in the server config or in the account JWT (depending on the security mode you are using).

If you partition a message stream into 3 (for example) then you could create 3 streams, each one capturing messages on a partition, and then you would run 3 consuming applications (for example) each subscribing to it's own stream consumer. You can modify the number of partitions in the subject mapping transform at any time (i.e. change the server config and signal the server to reload the config file, or push an updated account JWT), but up to you to start/stop the partitions' consuming applications according to your change.

Starting with NATS 2.10 you will be able to define subject mapping transform directly in the streams (i.e. the transform is defined as part of the stream definition)

**Comment by wallyqs** [comment]
Added in #536

**Comment by hungiito** [comment]
> Starting with NATS 2.10 you will be able to define subject mapping transform directly in the streams (i.e. the transform is defined as part of the stream definition)
@jnmoyne This is exciting! How can I subscribe to be notified when this feature is released?

**Comment by wallyqs** [comment]
@hungiito you can find an example here: #536 release of client should be out later today
