### ISSUE TITLE
Add subscription ID in Msg

### ISSUE THREAD

**Issue by charbonnierg** [nats-io/nats.py#427]
## Feature request

Would if possible to add the subscription ID as an attribute of `Msg` class ?

## Use case

We would like to emit logs with associated subscription IDs when processing messages

## Considered alternatives

I'm not aware of any easy way to access subscription ID within callback

### Current solution

Today we manually create a mapping of callbacks and subscription IDs, and we wrap callbacks in order to bind the subscription ID to our logger before calling callback (thus, logs emitted in callback have the correct subscription ID)

## Implementation

I'm willing to open a PR if feature request is accepted

**Comment by wallyqs** [comment]
This sounds good to me @charbonnierg

**Comment by charbonnierg** [comment]
I created #428 which is the solution I prefer, and I created #430 in case you don't want to introduce a breaking change.
