### ISSUE TITLE
Key-value store works incorrect

### ISSUE THREAD

**Issue by raprek** [nats-io/nats.py#449]
When key value store created according lib example [(example),](https://github.com/nats-io/nats.py/blob/main/examples/kv.py) you can not do actions with a key more than 1 time (set, delete and ect).

Reproduce
```
nc = await nats.connect()
js = nc.jetstream()
kv = await js.key_value(bucket='test')
await kv.put('16', b'2')
await kv.put('16', b'2')
```
Error: 
```
ServiceUnavailableError                   Traceback (most recent call last)
<ipython-input-241-1809010e4459> in <module>
----> 1 await kv.put('16', b'2')

/usr/local/lib/python3.9/site-packages/nats/js/kv.py in put(self, key, value)
    180         and return the revision number.
    181         """
--> 182         pa = await self._js.publish(f"{self._pre}{key}", value)
    183         return pa.seq
    184 

/usr/local/lib/python3.9/site-packages/nats/js/client.py in publish(self, subject, payload, timeout, stream, headers)
    128         resp = json.loads(msg.data)
    129         if 'error' in resp:
--> 130             raise nats.js.errors.APIError.from_error(resp['error'])
    131         return api.PubAck.from_response(resp)
    132 

/usr/local/lib/python3.9/site-packages/nats/js/errors.py in from_error(cls, err)
     78         code = err['code']
     79         if code == 503:
---> 80             raise ServiceUnavailableError(**err)
     81         elif code == 500:
     82             raise ServerError(**err)

ServiceUnavailableError: nats: ServiceUnavailableError: code=503 err_code=10077 description='maximum messages per subject exceeded'
```
According source code this happens due to `history = 1` default param in create_key_value [code](https://github.com/nats-io/nats.py/blob/160b946d3cdefec54a52938c0ce97575822f2a09/nats/js/client.py#L1013), combing with discard=api.DiscardPolicy.NEW [code](https://github.com/nats-io/nats.py/blob/160b946d3cdefec54a52938c0ce97575822f2a09/nats/js/client.py#L1039)

Set history -1 helps, BUT values under the key increasing after any action, because max_msgs set to -1 that leads to trash in history value.
Looks like discard should be set to api.DiscardPolicy.OLD or it would be great to have the opportunity to change more StreamConfig options through  create_key_value params. (at least discard policy )

**Comment by charbonnierg** [comment]
FWIW, I tried to reproduce using this script:


```python
import asyncio
import nats
import nats.js
import nats.js.errors


async def main() -> None:
    nc = await nats.connect()
    js = nc.jetstream()
    try:
        await js.delete_key_value("test-issue-449")
    except nats.js.errors.NotFoundError:
        pass
    await js.create_key_value(nats.js.api.KeyValueConfig("test-issue-449"))
    kv = await js.key_value(bucket="test-issue-449")
    for _ in range(1000):
        await kv.put("foo", b"bar")


if __name__ == "__main__":
    asyncio.run(main())
```

but I did not get any error. I also ran those line within an IPython session without any error.

**Comment by raprek** [comment]
Thanks for response. After update nats-py to 2.3.1 and server to 2.9.17 the issue has disappeared
