### ISSUE TITLE
Support for consumer backoff

### ISSUE THREAD

**Issue by csuriano23** [nats-io/nats.py#451]
Hi there,
from NATS v. 2.7.1 there is support for backoff in consumers (see [this](https://github.com/nats-io/nats-server/pull/2812)).

Any plans to support this in ConsumerConfig interface of the python client?

**Comment by bruth** [comment]
Hi @csuriano23. As you pointed out the `backoff` consumer config needs to be added, however `msg.nak()` does have a `delay` parameter: https://nats-io.github.io/nats.py/modules.html#nats.aio.msg.Msg.nak in case that is sufficient for your use case right now.

**Comment by csuriano23** [comment]
https://github.com/nats-io/nats.py/pull/483

**Comment by wallyqs** [comment]
Merged #483
