### ISSUE TITLE
Python 3.7 is not functional in 2.3.1

### ISSUE THREAD

**Issue by jarretlavallee** [nats-io/nats.py#456]
v2.3.1 with [Python 3.7](https://github.com/nats-io/nats.py/blob/main/pyproject.toml#L14) produces the following error.

```
AttributeError: '_asyncio.Task' object has no attribute 'get_name'
```

It looks like `get_name` was introduced in [Asyncio 3.8](https://docs.python.org/3.8/library/asyncio-task.html?highlight=task#asyncio.Task.get_name). `get_name` is only used once [here](https://github.com/nats-io/nats.py/blob/v2.3.1/nats/aio/subscription.py#L181).

**Comment by wallyqs** [comment]
Thanks for the report, will see if I can revert this...

**Comment by Lancetnik** [comment]
@wallyqs what do you think about remove python3.7 supporting since 2023-06-27? Python3.7 [EOF](https://devguide.python.org/versions/) soon. So I can update all repository code to Python3.8 features and setup linters and tests checks it's compability

**Comment by wallyqs** [comment]
@Lancetnik I would say yes, but given currently opened issue and other feedback I think it might be too soon, so maybe hold off on removing support for 3.7 for another month at least. What other 3.8 features do you think we should adopt btw?

**Comment by Lancetnik** [comment]
There no some many major features: ’:=’, TypedDict, AsyncMock and a little performance bust

**Comment by Lancetnik** [comment]
@wallyqs open PR with fixes

**Comment by justinfx** [comment]
Was this going to be tagged as 2.3.2 any time soon? I had previously hit the issues with 2.3.0 and 2.3.1 in python 3.7, and now this seems to be a remaining issue.

**Comment by samhodge-aiml** [comment]
This is causing me pain too.
