### ISSUE TITLE
Close method does not work on python less than 3.9

### ISSUE THREAD

**Issue by raprek** [nats-io/nats.py#478]
Method https://github.com/nats-io/nats.py/blob/7b6642685a3ebed7bde603649e93b62cbda42e9d/nats/aio/client.py#L624  does not work on python less that 3.9, because it calls fut.cancel("nats: connection is closed") [source code](https://github.com/nats-io/nats.py/blob/7b6642685a3ebed7bde603649e93b62cbda42e9d/nats/aio/client.py#L692). Err: ```cancel() takes no arguments (1 given)```
The problem is that argument in Future.cancel supports only from python 3.9 [docs](https://docs.python.org/3/library/asyncio-future.html), however due to project description nats-py supports: 
![image](https://github.com/nats-io/nats.py/assets/47252349/4524864f-2f7d-4c8a-a8ef-da640c530688)

**Comment by wallyqs** [comment]
Fixed in #479
