### ISSUE TITLE
hdr[k.strip()] = v.strip() AttributeError: 'Header' object has no attribute 'strip'

### ISSUE THREAD

**Issue by Muhammadali-Akbarov** [nats-io/nats.py#491]
### What version were you using?

In` nats-py==2.2.` sometimes this error occurs

### What environment was the server running in?

I have seen in linux and iMac with using python3.8

### Is this defect reproducible?

No

### Given the capability you are leveraging, describe your expectation?

-

### Given the expectation, what is the defect you are observing?

-

**Comment by wallyqs** [comment]
In +2.3.0 the parsing header code got rewritten and got a perf boost when using the `fast_mail_parser` dependency so likely this cannot be reproduced in newer versions so will close for now.
