### ISSUE TITLE
Can't install v2.4.0 with Poetry

### ISSUE THREAD

**Issue by diogobaeder** [nats-io/nats.py#495]
### What version were you using?

Client: v2.4.0

### What environment was the server running in?

Arch Linux x64

### Is this defect reproducible?

Yes: `$ poetry add nats-py`

### Given the capability you are leveraging, describe your expectation?

I should be able to install client v2.4.0, like I do with v2.3.1:

```
 $ poetry install
Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing nats-py (2.3.1)
```

### Given the expectation, what is the defect you are observing?

I can't install client v2.4.0:

```
 $ poetry install
Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing nats-py (2.4.0): Failed

  TypeError

  Can't instantiate abstract class IsolatedEnv with abstract methods make_extra_environ, python_executable

  at /usr/lib/python3.11/site-packages/poetry/installation/chef.py:109 in _prepare
      105│     ) -> Path:
      106│         from subprocess import CalledProcessError
      107│ 
      108│         with ephemeral_environment(self._env.python) as venv:
    → 109│             env = IsolatedEnv(venv, self._pool)
      110│             builder = ProjectBuilder(
      111│                 directory,
      112│                 python_executable=env.executable,
      113│                 scripts_dir=env.scripts_dir,
```

**Comment by wallyqs** [comment]
@diogobaeder which python version are you using?

**Comment by diogobaeder** [comment]
@wallyqs Python 3.11

**Comment by skewty** [comment]
How do you tell poetry that "nats" is actaully just "nats-py" package (alias)? I get warnings that nats package isn't part of project requirements everywhere I import it because it has no way of equating the two.

**Comment by diogobaeder** [comment]
BTW, I can install `nats-py` just fine now, with version 2.8.0; But I have the same issue as @skewty - it would make sense to open a new issue for this though.
