### ISSUE TITLE
`nats-py[nkeys]` won't install on Python 3.12.0

### ISSUE THREAD

**Issue by esjolander** [nats-io/nats.py#509]
### Observed behavior

`nats-py[nkeys]` has a dependency on `ed25519`, which errors on install:

```
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
```

This is because `ed25519` uses `versioneer`, which [has a bug](https://github.com/python-versioneer/python-versioneer/issues/375). There is [an issue](https://github.com/warner/python-ed25519/issues/20) against `ed25519`, but it seems to be a dead project. 
The right fix might be to [move to `pynacl`](https://github.com/nats-io/nats.py/issues/154), which does install on Python 3.12.

### Expected behavior

It should be possible to pull in `nkeys` on Python 3.12.

### Server and client version

Server and client versions don't matter.
I tested the latest `nats-py` release: `pip install 'nats-py[nkeys]==2.4.0'`

### Host environment

Ubuntu 22.04, x86-64, pyenv used for Python 3.12.

### Steps to reproduce

Install Python 3.12.0, then install `nats-py[nkeys]`

```console
$ python3 --version
Python 3.12.0
$ pip install 'nats-py[nkeys]==2.4.0'
```

**Comment by itssimon** [comment]
This is a showstopper that needs urgent attention IMO

**Comment by wallyqs** [comment]
yes, there will be a new release of nkeys with the replaced dependency this week

**Comment by RangeMachine** [comment]
Any update on this?

**Comment by strangemonad** [comment]
@wallyqs This seems related to this other issue I filed in the nkeys repo https://github.com/nats-io/nkeys.py/issues/10. If I force nkeys to point to the main branch of the git repo instead of pypi then this works (since it installs pynacl)

**Comment by itssimon** [comment]
Hey @wallyqs, It's been a few weeks since you promised the new release of nkeys. Can the community help in any way to make this happen soon?

**Comment by philpennock** [comment]
Someone raised this on Slack and I took a look.

So it looks like what has happened here is that we have both a `master` branch and a `main` branch, and `main` has switched to `pynacl` (thereby fixing this issue), but `master` has not, and `master` is still the default branch.

We're chasing this now.

**Comment by itssimon** [comment]
Looks like `main` is now the default branch in the `nkeys.py` repo, but to fix this issue we'd also need a release to PyPI.

**Comment by wallyqs** [comment]
nkeys version with pynacl support has been released today: https://github.com/nats-io/nkeys.py/releases/tag/v0.2.0
