### ISSUE TITLE
Add Service API

### ISSUE THREAD

**Issue by Jarema** [nats-io/nats.py#552]
### Proposed change

Implement Service API spec: https://github.com/nats-io/nats-architecture-and-design/blob/main/adr/ADR-32.md

### Use case

Simplify the development of NATS micro-services.

The design goal of the API is to reduce development to having a complexity similar to that of writing a NATS subscription, but then by using simple configuration, allow the specified metadata to allow for standardization of discovery and observability.

**Comment by yash97** [comment]
Hi can i work on this problem?

**Comment by Jarema** [comment]
Hi @yash97 

Contributions are very welcome!
However there is some work in progress. Let me find the branch and see if there was progress recently to avoid any duplication of efforts.

**Comment by charbonnierg** [comment]
You might want to check https://github.com/charbonats/nats-micro

There are some tests: https://github.com/charbonats/nats-micro/blob/main/tests/test_micro.py

**Comment by skewty** [comment]
@caspervonb seeing lots of issues w/o response / feedback and this python repo as a whole seems early beta at best based on issues being filed. Is the issue lack or time?  There is no "Contributors" section in the projects README. Are PRs welcome?

I can help with many of the issues if the existing team is willing to put the time into timely reviews / merges..  Right now my feeling is that NATS for python is a non starter and mostly dead project. Some transparency would be appreciated.

**Comment by skewty** [comment]
@caspervonb 
> Currently we're implementing the services API as-well as jetstream simplification. Both of these are expected to land roughly within the month.

It has been over 2 months now. Was the team able to achieve these goals?

**Comment by wallyqs** [comment]
yes the @skewty the services API was merged

**Comment by skewty** [comment]
My bad, I missed it in the change log somehow. I should probably finish my coffee before trying to do work. The team also did a wonderful job on documentation.

https://github.com/nats-io/nats-architecture-and-design/blob/main/adr/ADR-32.md

**Comment by blowback** [comment]
Many thanks for the long anticipated service API! Is there an equivalent of `services.client` in the JS sdk? i.e. something on which I can call  `ping()`  et al?
