### ISSUE TITLE
Add filtering to KV method returning all keys

### ISSUE THREAD

**Issue by Jarema** [nats-io/nats.py#575]
Here is the revised issue description:

# Description
The current method that returns all keys in the bucket does not support filtering specific keys. Adding this functionality would be beneficial, especially when working with large buckets.

# Details

Extract from ADR:
```go
	// KeysWithFilters returns a filtered list of keys in the bucket.
	// Historically this method returned a complete slice of all keys in the bucket,
	// however clients should return interable result.
	// Languages can implement the list of filters in most idiomatic way - as an iterator, variadic argument, slice, etc.
	// When multiple filters are passed, client library should check `consumer info` from `consumer create method` if the filters are matching,
	// as nats-server < 2.10 would ignore them.
	KeysWithFilters(filter []string) ([]string, error)
```

The new method should align with the current library API in terms of signature and behavior for retrieving all keys.

# Contribution
This is a good first issue for someone new to the project, as it should be based on the same underlying Ordered Consumer
that the method for receiving all keys is based on, plus the provided subject filters (and properly kv handled prefixes).

# References
- Reference ADR: https://github.com/nats-io/nats-architecture-and-design/blob/main/adr/ADR-8.md?plain=1#L139
- Reference ADR issue: [nats-io/nats-architecture-and-design#289](https://github.com/nats-io/nats-architecture-and-design/issues/289)

**Comment by aryan-py** [comment]
I would love to take this up as my first issue and would love any advice.

**Comment by somratdutta** [comment]
Ho @Jarema would love to have your comments on this [PR](https://github.com/nats-io/nats.py/pull/602).

**Comment by Jarema** [comment]
thanks @somratdutta ! We will take a look at that PR shortly!
