### ISSUE TITLE
Add `async for` support for consuming messages

### ISSUE THREAD

**Issue by wallyqs** [nats-io/nats.py#76]
Implement asynchronous iterator for the client: https://www.python.org/dev/peps/pep-0492/#asynchronous-iterators-and-async-for

```
sub = await sc.subscribe("foo")
async for msg in sub.messages:
    print("Received a message (seq={}): {}".format(msg.seq, msg.data))
```

**Comment by 1755** [comment]
Is anyone doing the issue? I can try to open PR to solve this

**Comment by wallyqs** [comment]
not that I'm aware of, @1755 feel to send PR and will take a look 👍

**Comment by wallyqs** [comment]
This is included in v1-dev branch already
