### ISSUE TITLE
Python NATS Client not able to achieve the desired performance

### ISSUE THREAD

**Issue by purDgr8** [nats-io/nats.py#99]
I have written a short python NATS Client that subscribes to a certain subject and then publishes 'n' number of requests to  the gNATSd and eventually to a NatsClient written in C. This C NatsClient then replies on the 'reply subject' mentioned in the publish_request call. The problem that I see is : all the publish_requests are sent very quickly from python Natsclient to gNATSd and then to the C Natsclient, but the response takes pretty long. I am sure that the bottleneck here is somewhere in the subscribe and the response_handle part of the code and not in the C Natsclient that sends the responses. Here is the code snippet :

    def connect(self):
        self.loop.run_until_complete(self.nc.connect(servers=["nats://localhost:4222"]))

    def disconnect(self):
        return self.loop.run_until_complete(self.nc.close())

    def send(self, request_number):
        self.loop.run_until_complete(self.pub())

    def recv(self):
        self.loop.run_until_complete(self.sub())

    def wait_for_msg(self):
        self.loop.run_until_complete(self.wait())

    async def pub(self):
        await self.nc.publish_request(self.subject, self.reply, json.dumps(self.data1).encode())

    async def sub(self):
        async def response_handle(msg):
            message = json.loads(msg.data.decode())
            self.msgs.append(message)
            #self.future.set_result(message)

        await self.nc.subscribe(self.reply, cb = response_handle)

    async def wait(self):
        try:
            msg = await asyncio.wait_for(self.future, 1)
        except asyncio.TimeoutError:
            print("NATS: No more messages to receive exiting")

Those methods are being called in the following order :

    def send_recv(self):
        self.nats.recv()
        for i in range(100):
            self.nats.send()
        self.nats.wait_for_msg()

    def run(self):
        self.nats.connect()
        t = time.time()
        self.send_recv()
        self.nats.flush_nats()
        total_time = time.time() - t
        self.nats.print()
        print ("Time taken:", total_time)

Also, a general observation is that on increasing the number of response from 100 to say 10000, I see that the program exits after receiving only a few responses and after raising the exception "NATS: No more messages to receive exiting". However, if I raise the timeout value to a greater number here : await asyncio.wait_for(self.future, 1) I do get all the responses.

Could someone please suggest what can be done to reduce the time for processing all those requests.

**Comment by purDgr8** [comment]
We are basically looking for performance metrics around 60000msg/sec. By messages I mean the the time taken for both, the request + the response. Currently, we are getting pretty bad timings for 60k(around 47 secs).

**Comment by wallyqs** [comment]
@purDgr8 have you looked at the benchmark scripts here?  https://github.com/nats-io/asyncio-nats/blob/master/benchmark/latency_async_perf.py

**Comment by purDgr8** [comment]
This is what I see after running the script :purdgr8$ python3 latency_async_perf.py
Sending 10000 request/responses on [test]
#######################################
Test completed : 0.26 ms avg request/response latency (failures=0)

**Comment by wallyqs** [comment]
@purDgr8 using the benchmark scripts locally I'm getting around the following, what size are the payloads of the messages?
```
python3 benchmark/latency_perf.py -n 60000
Sending 60000 request/responses on [test]
...
Test completed : 0.326 ms avg request/response latency
```

**Comment by wallyqs** [comment]
Also with uvloop results fare a bit better, if can give it a try:
```
$ python3 -m pip install uvloop
$ python3 benchmark/latency_async_perf.py -n 60000
Sending 60000 request/responses on [test]
...
Test completed : 0.23 ms avg request/response latency (failures=0)
```

**Comment by purDgr8** [comment]
The payload is 368 B for every req. Also,  tried for 60K with the uvloop, below is the result : 

$ python3 latency_async_perf.py
Sending 60000 request/responses on [test]
###############################################################################################################################################################################################################################################
Test completed : 0.27 ms avg request/response latency (failures=0)

**Comment by wallyqs** [comment]
Right, so think this client should be able to handle that type of load, there might be something blocking in the original code that is preventing the processing the messages.  Maybe could be possible to borrow some of the code from the benchmark script to verify the perf or is there something else that the script should do besides request/response?

**Comment by purDgr8** [comment]
Hello Waldamer, I did use the benchmark script by editing the subject and payload data according to my needs. It however did not help in improving the performance. The C natsclient is taking around 19 secs to process all the requests and to send it back to the gNATSd, however the python natsclient that I have written using the benchmark script still takes around ~47sec to get all the responses. 

Now, referring to the python client that I have shared earlier has the following line : 

msg = await asyncio.wait_for(self.future, **1**) --> when I change this timeout value to a higher number say 30, I am able to get all the responses but this 30 sec timeout is added up in the actually time of 19sec + 30 sec = ~49 sec. If I reduce this time to a lower number (say 20 sec) I am not able to receive all the response, the program exits after processing only a few number of responses say 33000.

Could you suggest how can we deal with this timeout thing.

**Comment by wallyqs** [comment]
since it is a future, you could stop earlier once the future is done by using set_result on it, that way do not have to hang until wait_for is done

**Comment by purDgr8** [comment]
I tried as u suggested by uncommenting the self.future.set_result(message) part of my code as below:

async def sub(self):
    async def response_handle(msg):
        message = json.loads(msg.data.decode())
        self.msgs.append(message)
        #self.future.set_result(message) ---->> uncommented this line.

I see two problems when I do this : 

1. While I tried sending 55000 message, only 38504 messages were actually sent to the gNATSd
2. I could receive response for only 1938 requests.

**Comment by wallyqs** [comment]
shouldn't the future.set_result be called when receiving all the messages? If you create a gist/repo with the example so that I can run it happy to take a look and experiment with the code further

**Comment by purDgr8** [comment]
yes, we are calling the future.set_result while receiving all the messages : 

async def sub(self):
    async def **response_handle**(msg):
        message = json.loads(msg.data.decode())
        self.msgs.append(message)
        **self.future.set_result(message)**

    await self.nc.subscribe(self.reply, **cb = response_handle**)

I guess this is what you are implying.

**Comment by purDgr8** [comment]
the code snippet got pasted in a funny way, but yes, if u see the code, future.set_result is being called as part of the cb which is being used in the subscribe part.

**Comment by purDgr8** [comment]
I have added you as collaborator to my repo. I would be glad if you can have a look and suggest improvements. :)

**Comment by wallyqs** [comment]
Hi @purDgr8 seems like didn't get notification to join the repo... could you share the link and then can have a look? thanks :)

**Comment by wallyqs** [comment]
Closing for now but feel free to reopen or reach out to follow up 🙂
